# Generated by Django 4.2 on 2023-04-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertDecisionMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_name', models.CharField(max_length=100)),
                ('alternatives', models.JSONField()),
                ('criteria', models.JSONField()),
                ('values', models.JSONField()),
            ],
        ),
    ]
