# Generated by Django 4.2 on 2023-04-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topsis', '0002_alternative_criterion'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertdecisionmatrix',
            name='scale',
            field=models.CharField(default='3', max_length=10),
        ),
    ]
